vsecurity:
  jwt:
    exp-min: 15

spring:
  application:
    name: MedicalRecord

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medical_record?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:12345678}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hidden method:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

# logging:
#   level:
#     org.springframework.security: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.orm.jdbc.bind: TRACE
